on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - uses: docker/build-push-action@v5
        with:
          context: ./server/
          tags: crispy-disco
          outputs: type=docker,dest=/tmp/myimage.tar
      - uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      - uses: actions/checkout@v3
      - run: sam build -t .github/files/lambda.yaml
      - run: |
          sam local start-lambda --parameter-overrides TAG=crispy-disco --warm-containers EAGER &
          while sleep 1; do >/dev/tcp/localhost/3001 && break; done
      - run: |
          export AWS_ACCESS_KEY_ID=x
          export AWS_SECRET_ACCESS_KEY=x
          export AWS_REGION=us-east-1
          export AWS_ENDPOINT_URL=http://localhost:3001
          ./test.sh
