on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:server'
          load: true
          tags: crispy-disco
      - run: sam build
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - run: sam local start-lambda --warm-containers EAGER &
      - run: |
          export AWS_ACCESS_KEY_ID=x
          export AWS_SECRET_ACCESS_KEY=x
          export AWS_REGION=us-east-1
          export AWS_ENDPOINT_URL=http://localhost:3001
          ./test.sh
