on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - uses: docker/build-push-action@v5
        with:
          context: ./server/
          tags: crispy-disco
          outputs: type=docker,dest=/tmp/myimage.tar
      - uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      - uses: actions/checkout@v3
      - run: sam build -t .github/files/lambda.yaml
      - run: |
          sam local generate-event apigateway http-api-proxy \
          | jq '.rawPath="/"|.requestContext.http.method="GET"' \
          | sam local invoke --parameter-overrides TAG=crispy-disco -e - \
          | tee /dev/stderr \
          | jq -e '.statusCode==200'
